# Generated by Django 3.2.20 on 2023-08-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_auto_20230820_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email_address',
        ),
    ]
